dist: trusty
sudo: false
language: c
script: CFLAGS="-O2 -Werror -Wno-unused-result $CFLAGS_EXTRA" make pkg
compiler:
- clang
- gcc
env:
- CFLAGS_EXTRA=
- CFLAGS_EXTRA=-m32
addons:
  apt:
    packages:
    - gcc-multilib
