dist: trusty
sudo: false
language: c
script: scripts/travis-build.sh
compiler:
- gcc
- clang
env:
- CFLAGS=
- CFLAGS=-m32
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-multilib
    - gcc-6
    - gcc-6-multilib
